server:
  port: 8888
github:
  client:
    id: e05d34e830a2eaab39fb
    secret: ea3c75dd2428fac8b217eec32bcbeccee3ab368d
  redirect:
    uri: http://localhost:8888/callback
ucloud:
  ufile:
    public-key: TOKEN_b090eb86-2126-40eb-84d3-af7a5b8c0961
    private-key: 8a6c98f6-8464-4049-a285-bfbd32102aa3
    bucket-name: batcave
    region: cn-bj
    suffix: ufileos.com
    expires: 315360000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: ledon0909
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: life.ledon.community.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    max-size: 100MB
    max-history: 30
  level:
    root: info
    life:
      ledon:
        community:
          mapper: debug
  path: logs